name: Release container

on:
  push:
    branches: ["main"]

jobs:
  release:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-container-release.yml@de87dbad3eccace3cffdbccbe78c2fc98f77a68c # v1.1.0
