name: Release container

on:
  push:
    branches: ["main"]

jobs:
  release:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-container-release.yml@8339f7f8349d4e9824ffe95a3941cd9b691c6135 # v1.1.1
