name: Repository CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  security:
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-repository-ci.yml@b63d41bfe270b99ff69afa069f3c48fdfc4311d0 # v1.0.0
    with:
      run-infrastructure-static: true
