name: Repository CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  security:
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-repository-ci.yml@3b3d131bfda6078c38fd2bec0c1acd58f55b8726
