name: Repository CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  security:
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-repository-ci.yml@000869f3edd295b10382a4fa72b5b387ecc702c6 # v1.0.0
    with:
      run-infrastructure-static: true
