name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-saas-ci.yml@de87dbad3eccace3cffdbccbe78c2fc98f77a68c # v1.1.0
