name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: LouisVannobel/projetV0-pipelines/.github/workflows/reusable-saas-ci.yml@bc5084f80c4aef7a1d1393fc3f5617fc46a6fb6d # v1.3.0
